version: '3'

services:
  coretail:
    image: ghcr.io/bellrocktech/coretail
    privileged: false
    container_name: coretail
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "10.0.0.153:53:53/tcp"
      - "10.0.0.153:53:53/udp"
    environment:
      - TS_AUTH_KEY=${TS_AUTH_KEY}
      - HOSTNAME=coretail
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
